/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: pandan (https://sketchfab.com/pandan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nike-air-mag-15ef47bad0aa4666b459cf78261abce5
title: Nike Air Mag
*/
import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/shoe3.glb");


  // Clone materials and set colors
  // const [laceMaterial] = useState(() => materials["Laces Material"].clone());
  // const [MainMaterial] = useState(() => materials["Main Body Material"].clone());
  // laceMaterial.color.set("#000000");
  // MainMaterial.color.set("#000000");


  return (
    <group ref={group} {...props} dispose={null} scale={10} rotation={[0, 0, 0.3]} >
      <group position={[0, -0.025, 0]}>
        <mesh geometry={nodes.Plane040.geometry} material={materials["Sole Material"]} />
        <mesh geometry={nodes.Plane040_1.geometry} material={materials["Insole Material right"]} />
        <mesh geometry={nodes.Plane040_2.geometry} material={materials["Main Body Material"]} />
        <mesh geometry={nodes.Plane040_3.geometry} material={materials["Main Shoe Inside"]} />
        <mesh
          geometry={nodes.Laces005.geometry}
          material={materials["Laces Material"]}
          position={[-0.087, 0.081, -0.001]}
          rotation={[0, 0, 0.45]}
        />
        <mesh
          geometry={nodes.Nike_Logo_left004.geometry}
          material={materials["Logo left Material"]}
          position={[0.213, 0.065, 0.033]}
          rotation={[0, 0.174, 0]}
        />
        <mesh
          geometry={nodes.Nike_Logo_right004.geometry}
          material={materials["Logo right Material"]}
          position={[0.213, 0.065, -0.087]}
          rotation={[0, 0.044, 0]}
        />
        <mesh
          geometry={nodes.Shoe_Flap008.geometry}
          material={materials["Tag materialright.001"]}
          position={[0, -0.005, 0]}
        />
        <mesh
          geometry={nodes.Shoe_Flap009.geometry}
          material={materials["Flap Material.002"]}
          position={[0, -0.005, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/shoe3.glb");
